### PR TITLE
Quiet mode

### PR DESCRIPTION
**Pull request by hawson**

### CODE REVIEW

**Comment by Napsty** [comment]
Nice. Tested.

```
mintp ~ # /tmp/check_smart.pl -g "/dev/sd[a-z]" -i ata
UNKNOWN: [/dev/sdd] - No health status line found --- [/dev/sda] - Device is clean --- [/dev/sdb] - Device is clean --- [/dev/sdc] - Device is clean|

mintp ~ # /tmp/check_smart.pl -g "/dev/sd[a-z]" -i ata -q
UNKNOWN: [/dev/sdd] - No health status line found --- Other drives OK|
```

**Comment by Napsty** [comment]
@hawson change around line 537 like this:

```
                if($exit_status_local ne 'OK'){
                  if ($opt_g) {
                        $status_string = $label.join(', ', @error_messages);
                  }
                  else {
                        $status_string = "Drive $model S/N $serial: ";
                        $status_string .= join(', ', @error_messages);
                  }
``` 

And the output is shown for single drive checks again.

**Comment by hawson** [comment]
This look better?  Here are my tests cases on a host with a bunch of drives, one of which has a fault (`sdf`):
=== drive sda LOUD ===
```
./check_smart.pl -i auto -d /dev/sda
OK: Drive  ST4000NM0033-9ZM170 S/N 12431243: no SMART errors detected. |Raw_Read_Error_Rate=100414322 Spin_Up_Time=0 Start_Stop_Count=24 Reallocated_Sector_Ct=0 Seek_Error_Rate=2957989499 Power_On_Hours=39141 Spin_Retry_Count=0 Power_Cycle_Count=24 End-to-End_Error=0 Reported_Uncorrect=0 Command_Timeout=0 High_Fly_Writes=0 Airflow_Temperature_Cel=37 G-Sense_Error_Rate=0 Power-Off_Retract_Count=21 Load_Cycle_Count=1647 Temperature_Celsius=37 Hardware_ECC_Recovered=100414322 Current_Pending_Sector=0 Offline_Uncorrectable=0 UDMA_CRC_Error_Count=0
```

=== drive sda QUIET ===
```
./check_smart.pl -i auto -d /dev/sda -q
OK: Drive  ST4000NM0033-9ZM170 S/N 12341243: no SMART errors detected. |Raw_Read_Error_Rate=100414322 Spin_Up_Time=0 Start_Stop_Count=24 Reallocated_Sector_Ct=0 Seek_Error_Rate=2957989503 Power_On_Hours=39141 Spin_Retry_Count=0 Power_Cycle_Count=24 End-to-End_Error=0 Reported_Uncorrect=0 Command_Timeout=0 High_Fly_Writes=0 Airflow_Temperature_Cel=37 G-Sense_Error_Rate=0 Power-Off_Retract_Count=21 Load_Cycle_Count=1647 Temperature_Celsius=37 Hardware_ECC_Recovered=100414322 Current_Pending_Sector=0 Offline_Uncorrectable=0 UDMA_CRC_Error_Count=0
```

=== drive sdf LOUD ===
```
./check_smart.pl -i auto -d /dev/sdf
WARNING: Drive  WDC WD4002FYYZ-01B7CB0 S/N 23452345:  Reallocated_Sector_Ct is non-zero (1)|Raw_Read_Error_Rate=0 Throughput_Performance=78 Spin_Up_Time=582 Start_Stop_Count=6 Reallocated_Sector_Ct=1 Seek_Error_Rate=0 Seek_Time_Performance=26 Power_On_Hours=1722 Spin_Retry_Count=0 Power_Cycle_Count=6 Power-Off_Retract_Count=58 Load_Cycle_Count=58 Temperature_Celsius=34 Reallocated_Event_Count=1 Current_Pending_Sector=0 Offline_Uncorrectable=0 UDMA_CRC_Error_Count=0
```

=== drive sdf QUIET ===
```
./check_smart.pl -i auto -d /dev/sdf -q
WARNING: Drive  WDC WD4002FYYZ-01B7CB0 S/N 23452345:  Reallocated_Sector_Ct is non-zero (1)|Raw_Read_Error_Rate=0 Throughput_Performance=78 Spin_Up_Time=582 Start_Stop_Count=6 Reallocated_Sector_Ct=1 Seek_Error_Rate=0 Seek_Time_Performance=26 Power_On_Hours=1722 Spin_Retry_Count=0 Power_Cycle_Count=6 Power-Off_Retract_Count=58 Load_Cycle_Count=58 Temperature_Celsius=34 Reallocated_Event_Count=1 Current_Pending_Sector=0 Offline_Uncorrectable=0 UDMA_CRC_Error_Count=0
```

=== group LOUD ===
```
./check_smart.pl -i auto -g /dev/sd[a-z]
WARNING: [/dev/sdf] - Reallocated_Sector_Ct is non-zero (1) --- [/dev/sda] - Device is clean --- [/dev/sdb] - Device is clean --- [/dev/sdc] - Device is clean --- [/dev/sdd] - Device is clean --- [/dev/sde] - Device is clean --- [/dev/sdg] - Device is clean --- [/dev/sdh] - Device is clean --- [/dev/sdi] - Device is clean --- [/dev/sdj] - Device is clean|
```

=== group QUIET ===
```
./check_smart.pl -i auto -g /dev/sd[a-z] -q
WARNING: [/dev/sdf] - Reallocated_Sector_Ct is non-zero (1) --- Other drives OK|
```

**Comment by Napsty** [comment]
Thanks!

**Pull request merged**
