### PR TITLE
Allow script to run outside of nagios folder, and updated wiki url

### PR DESCRIPTION
**Pull request by behrendsj**
This PR allows the script to live and run outside of the nagios plugin dir.
There is also an update to the wiki url referenced in the script.

### CODE REVIEW

**Comment by behrendsj** [comment]
@Napsty  - Ping!

**Comment by Napsty** [comment]
Pong! First need to test it on multi os  before I merge

**Comment by Napsty** [comment]
PR only works for Linux. I'll manually merge this PR and then add a bugfix for FreeBSD after the merge.

**Comment by Napsty** [comment]
Manually merged in commit 5a7e5ac9aa41a4e22cdb29586a10ab93328371cb

**Pull request closed without merging**
